server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:./h2data/survey-manager-backend-application-h2
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
    change-log: classpath:migration/liquibase-changelog.xml