server:
  port: 8081
files:
  upload-dir: "/var/lib/caffplacc/files"
  preview-dir: "/var/lib/caffplacc/previews"
spring:
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
  datasource:
    url: jdbc:h2:file:./h2data/survey-manager-backend-application-h2
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
    change-log: classpath:migration/liquibase-changelog.xml
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
logging:
  file:
    path: logs