server:
  port: 8081
files:
  upload-dir: "./files"
  preview-dir: "./previews"
spring:
  datasource:
    url: jdbc:h2:file:./h2data/caffplacc-backend-application-h2
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
    change-log: classpath:migration/liquibase-changelog.xml
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB