server:
  port: 8081
files:
  upload-dir: "./files"
  preview-dir: "./previews"
spring:
  datasource:
    url: jdbc:postgresql://database:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:migration/liquibase-changelog.xml
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB